import type { TaskCacheSpec } from "../core/task";
import { Script, languageFor, type LanguageName } from "../script";

/**
 * Language used for cache steps that need structured data, zstd piping, and
 * cross-platform file ops — currently the compressed PVC and all GCS paths.
 * Centralized here so nushell is named in exactly one place rather than via
 * hand-written `#!/usr/bin/env nu` shebangs scattered across the backends.
 */
export const COMPRESSED_CACHE_LANGUAGE: LanguageName = "nushell";

/**
 * Portable default for cache steps whose logic is expressible in POSIX sh —
 * the uncompressed PVC restore/save. Keeping this on `sh` means the default
 * cache path mandates no nushell in the cache image.
 */
export const PORTABLE_CACHE_LANGUAGE: LanguageName = "sh";

/**
 * Wraps a cache-step body in a {@link Script} for the given language so the
 * shebang and `log` preamble are generated by the {@link ScriptLanguage} plugin
 * at synth time, rather than hand-written in each backend. Bodies call the
 * plugin's `log` helper and prefix their own step label.
 */
export function cacheScript(body: string, language: LanguageName): Script {
    return new Script(languageFor(language), body);
}

/** Returns the zstd thread flag. Pass `defaultMulti=true` for backends that default to multi-threaded (e.g. GCS). */
export function threadFlag(c: TaskCacheSpec, defaultMulti = false): string {
    const multi = c.multiThreadCompression ?? defaultMulti;
    return multi ? "-T0" : "-T1";
}

/** Returns the nushell hash-computation expression for the given key files. */
export function hashExpr(c: TaskCacheSpec): string {
    if (c.key.length === 0) {
        return `let hash = ("" | hash sha256 | str substring 0..15)`;
    }
    const keyFileList = c.key.map((f) => `"${f}"`).join(", ");
    return `let hash = (
  [${keyFileList}]
  | each { |f| if ($f | path exists) { open --raw $f } else { "" } }
  | str join | hash sha256 | str substring 0..15
)`;
}
