import { Construct } from "constructs";
import { ApiObject, Chart, ChartProps } from "cdk8s";
import { GitHubVcsProvider } from "../lib/triggers/github-vcs-provider";
import type { VcsProvider, VcsProviderCtx } from "../lib/triggers/vcs-provider";
import { TRIGGER_EVENTS } from "../lib/core/trigger-events";

/** Properties for the {@link TektonInfraChart}. */
export interface TektonInfraChartProps extends ChartProps {
    /** Kubernetes namespace for all infrastructure resources. */
    namespace: string;
    /** Pipeline name referenced by the push trigger. */
    pushPipelineRef?: string;
    /** Pipeline name referenced by the pull request trigger. */
    pullRequestPipelineRef?: string;
    /** Pipeline name referenced by the tag trigger. */
    tagPipelineRef?: string;
    /** Optional prefix prepended to all resource names. */
    namePrefix?: string;
    /** Kubernetes Secret reference for GitHub webhook validation. */
    webhookSecretRef?: { secretName: string; secretKey: string };
    /** Pipeline param name for the repository URL. Defaults to `"url"`. */
    urlParam?: string;
    /** Pipeline param name for the git revision. Defaults to `"revision"`. */
    revisionParam?: string;
    /** Pipeline param name that receives the git ref. */
    gitRefParam?: string;
    /** PVC size for the ephemeral pipeline workspace. Defaults to `"1Gi"`. */
    workspaceStorageSize?: string;
    /** StorageClass for the ephemeral workspace PVC. Omitted when not set — cluster default applies. */
    workspaceStorageClass?: string;
    /** Access modes for the ephemeral workspace PVC. Defaults to `["ReadWriteOnce"]`. */
    workspaceAccessModes?: string[];
    /** Persistent cache volumes to provision as PVCs and bind in every PipelineRun. */
    caches?: {
        workspaceName: string;
        claimName: string;
        storageSize: string;
        storageClassName?: string;
        /** Access modes for this cache PVC. Defaults to `["ReadWriteOnce"]`. */
        accessModes?: string[];
    }[];
    /**
     * Pod-level security context merged on top of `DEFAULT_POD_SECURITY_CONTEXT` for every
     * PipelineRun pod generated by the trigger templates.
     */
    defaultPodSecurityContext?: Record<string, unknown>;
    /** Annotations merged into every PipelineRun generated by the trigger templates. */
    pipelineRunAnnotations?: Record<string, string>;
    /** Additional annotations to apply to the generated ServiceAccount. */
    serviceAccountAnnotations?: Record<string, string>;
    /**
     * VCS provider implementations used to build trigger resources.
     * Defaults to `[new GitHubVcsProvider()]`.
     */
    providers?: VcsProvider[];
}

/**
 * cdk8s Chart that generates the shared trigger infrastructure:
 * - ServiceAccount and RBAC (RoleBinding + ClusterRoleBinding)
 * - PersistentVolumeClaims for any declared cache workspaces
 * - TriggerBindings and TriggerTemplates for push, PR, and tag events
 * - EventListener with GitHub interceptors and CEL filters
 */
export class TektonInfraChart extends Chart {
    constructor(scope: Construct, id: string, props: TektonInfraChartProps) {
        super(scope, id, props);

        const namespace = props.namespace;
        const p = props.namePrefix ? `${props.namePrefix}-` : "";
        const serviceAccountName = `${p}tekton-triggers`;

        // ── RBAC ─────────────────────────────────────────────────────────────────

        new ApiObject(this, "service-account", {
            apiVersion: "v1",
            kind: "ServiceAccount",
            metadata: {
                name: serviceAccountName,
                namespace,
                ...(props.serviceAccountAnnotations && {
                    annotations: props.serviceAccountAnnotations,
                }),
            },
        });

        new ApiObject(this, "role-binding", {
            apiVersion: "rbac.authorization.k8s.io/v1",
            kind: "RoleBinding",
            metadata: { name: `${p}tekton-triggers-eventlistener`, namespace },
            roleRef: {
                apiGroup: "rbac.authorization.k8s.io",
                kind: "ClusterRole",
                name: "tekton-triggers-eventlistener-roles",
            },
            subjects: [{ kind: "ServiceAccount", name: serviceAccountName }],
        });

        new ApiObject(this, "cluster-role-binding", {
            apiVersion: "rbac.authorization.k8s.io/v1",
            kind: "ClusterRoleBinding",
            metadata: { name: `${p}tekton-triggers-eventlistener` },
            roleRef: {
                apiGroup: "rbac.authorization.k8s.io",
                kind: "ClusterRole",
                name: "tekton-triggers-eventlistener-clusterroles",
            },
            subjects: [
                { kind: "ServiceAccount", name: serviceAccountName, namespace },
            ],
        });

        // ── Cache PVCs ────────────────────────────────────────────────────────────

        for (const cache of props.caches ?? []) {
            const pvcSpec: Record<string, unknown> = {
                accessModes: cache.accessModes ?? ["ReadWriteOnce"],
                resources: { requests: { storage: cache.storageSize } },
            };
            if (cache.storageClassName) {
                pvcSpec.storageClassName = cache.storageClassName;
            }
            new ApiObject(this, `cache-pvc-${cache.workspaceName}`, {
                apiVersion: "v1",
                kind: "PersistentVolumeClaim",
                metadata: { name: cache.claimName, namespace },
                spec: pvcSpec,
            });
        }

        // ── Triggers ──────────────────────────────────────────────────────────────

        const cacheWorkspaces = (props.caches ?? []).map((c) => ({
            workspaceName: c.workspaceName,
            claimName: c.claimName,
        }));

        // Ordered list of (pipelineRef, event) pairs — push and PR are always
        // present (matching existing behavior); tag is conditional.
        const triggerEntries: { pipelineRef: string; event: TRIGGER_EVENTS }[] = [
            { pipelineRef: props.pushPipelineRef ?? "push-pipeline", event: TRIGGER_EVENTS.PUSH },
            { pipelineRef: props.pullRequestPipelineRef ?? "pull-request-pipeline", event: TRIGGER_EVENTS.PULL_REQUEST },
            ...(props.tagPipelineRef
                ? [{ pipelineRef: props.tagPipelineRef, event: TRIGGER_EVENTS.TAG }]
                : []),
        ];

        const ctx: VcsProviderCtx = {
            namespace,
            namePrefix: props.namePrefix,
            webhookSecretRef: props.webhookSecretRef,
            urlParam: props.urlParam,
            revisionParam: props.revisionParam,
            gitRefParam: props.gitRefParam,
            workspaceStorageSize: props.workspaceStorageSize,
            workspaceStorageClass: props.workspaceStorageClass,
            workspaceAccessModes: props.workspaceAccessModes,
            cacheWorkspaces,
            defaultPodSecurityContext: props.defaultPodSecurityContext,
            pipelineRunAnnotations: props.pipelineRunAnnotations,
            allEvents: triggerEntries.map((e) => e.event),
        };

        const providers = props.providers ?? [new GitHubVcsProvider()];

        // ── EventListener ─────────────────────────────────────────────────────────

        const triggers: Record<string, unknown>[] = [];
        for (const { pipelineRef, event } of triggerEntries) {
            const provider = providers.find((p) =>
                p.supportedEvents.includes(event),
            );
            if (!provider) {
                throw new Error(
                    `TektonInfraChart: no VcsProvider found for event "${event}"`,
                );
            }
            const contribution = provider.buildTrigger(this, pipelineRef, event, ctx);
            triggers.push(contribution.eventListenerEntry);
        }

        new ApiObject(this, "event-listener", {
            apiVersion: "triggers.tekton.dev/v1beta1",
            kind: "EventListener",
            metadata: { name: `${p}github-listener`, namespace },
            spec: {
                serviceAccountName,
                triggers,
            },
        });
    }
}
