import type { CatalogMetadata } from '../../core/catalog';
import { DEFAULT_CATALOG_PLATFORMS } from '../../core/catalog';

/** One row of a Tekton `spec.params` / `spec.results` / `spec.workspaces` array. */
interface SpecEntry {
  name: string;
  type?: string;
  description?: string;
  default?: unknown;
  optional?: boolean;
}

/** Reads one of the array fields off a Task spec, tolerating its absence. */
function entries(spec: Record<string, unknown>, field: string): SpecEntry[] {
  const value = spec[field];
  return Array.isArray(value) ? (value as SpecEntry[]) : [];
}

/** Escapes the one character that would break a markdown table cell. */
function cell(value: string): string {
  return value.replace(/\|/g, '\\|');
}

/** Renders a default value the way a reader would type it back. */
function defaultCell(value: unknown): string {
  if (value === undefined) return '—';
  if (Array.isArray(value)) return value.length === 0 ? '`[]`' : value.map(v => `\`${String(v)}\``).join(', ');
  return `\`${String(value)}\``;
}

/** A markdown table, or nothing at all when there are no rows to put in it. */
function table(heading: string, columns: string[], rows: string[][]): string[] {
  if (rows.length === 0) return [];
  return [
    `## ${heading}`,
    '',
    `| ${columns.join(' | ')} |`,
    `|${columns.map(() => '---').join('|')}|`,
    ...rows.map(r => `| ${r.join(' | ')} |`),
    '',
  ];
}

/** Inputs for {@link catalogReadme}. */
export interface CatalogReadmeOptions {
  /** Catalog entry name — the task's declared name, without any project prefix. */
  name: string;
  /** The entry's catalog metadata. */
  catalog: CatalogMetadata;
  /** The emitted `Task` spec, read for params, results and workspaces. */
  spec: Record<string, unknown>;
  /** Catalog the entry is published to, as it appears in the `hub` resolver's params. */
  catalogName: string;
}

/**
 * Renders the `README.md` that ships beside a catalog entry.
 *
 * Generated rather than hand-written because a catalog README is a restatement of the
 * task's own params, results and workspaces — and a hand-written one rots the first time a
 * param is added. Everything here comes from the manifest being published, so the two
 * cannot disagree.
 */
export function catalogReadme(opts: CatalogReadmeOptions): string {
  const { name, catalog, spec, catalogName } = opts;
  const platforms = catalog.platforms ?? DEFAULT_CATALOG_PLATFORMS;

  const lines: string[] = [
    `# ${catalog.displayName ?? name}`,
    '',
    catalog.description,
    '',
    `<!-- Generated by tektonic from the '${name}' task definition. Do not edit by hand. -->`,
    '',
    '## Install',
    '',
    'Reference it from a Tekton pipeline through the hub resolver:',
    '',
    '```yaml',
    'taskRef:',
    '  resolver: hub',
    '  params:',
    `    - name: catalog`,
    `      value: ${catalogName}`,
    `    - name: name`,
    `      value: ${name}`,
    `    - name: version`,
    `      value: "${catalog.version}"`,
    '```',
    '',
    'Or, from a tektonic project:',
    '',
    '```ts',
    `new HubTaskRef({ catalog: '${catalogName}', taskName: '${name}', version: '${catalog.version}' })`,
    '```',
    '',
  ];

  lines.push(
    ...table(
      'Parameters',
      ['Name', 'Type', 'Description', 'Default'],
      entries(spec, 'params').map(p => [
        `\`${p.name}\``,
        `\`${p.type ?? 'string'}\``,
        cell(p.description ?? '—'),
        defaultCell(p.default),
      ]),
    ),
  );

  lines.push(
    ...table(
      'Results',
      ['Name', 'Type', 'Description'],
      entries(spec, 'results').map(r => [
        `\`${r.name}\``,
        `\`${r.type ?? 'string'}\``,
        cell(r.description ?? '—'),
      ]),
    ),
  );

  lines.push(
    ...table(
      'Workspaces',
      ['Name', 'Optional', 'Description'],
      entries(spec, 'workspaces').map(w => [
        `\`${w.name}\``,
        w.optional ? 'yes' : 'no',
        cell(w.description ?? '—'),
      ]),
    ),
  );

  lines.push('## Platforms', '', platforms.map(p => `\`${p}\``).join(', '), '');

  if (catalog.categories && catalog.categories.length > 0) {
    lines.push('## Categories', '', catalog.categories.join(', '), '');
  }
  if (catalog.tags && catalog.tags.length > 0) {
    lines.push('## Tags', '', catalog.tags.map(t => `\`${t}\``).join(', '), '');
  }

  return `${lines.join('\n')}`;
}
