import type { TaskCacheSpec } from "../core/task";
import { Script, languageFor, type LanguageName } from "../script";

/**
 * Language used for cache steps that need structured data, zstd piping, and
 * cross-platform file ops — currently the compressed PVC and all GCS paths.
 * Centralized here so nushell is named in exactly one place rather than via
 * hand-written `#!/usr/bin/env nu` shebangs scattered across the backends.
 */
export const COMPRESSED_CACHE_LANGUAGE: LanguageName = "nushell";

/**
 * Portable default for cache steps whose logic is expressible in POSIX sh —
 * the uncompressed PVC restore/save. Keeping this on `sh` means the default
 * cache path mandates no nushell in the cache image.
 */
export const PORTABLE_CACHE_LANGUAGE: LanguageName = "sh";

/**
 * Wraps a cache-step body in a {@link Script} for the given language so the
 * shebang and `log` preamble are generated by the {@link ScriptLanguage} plugin
 * at synth time, rather than hand-written in each backend. Bodies call the
 * plugin's `log` helper and prefix their own step label.
 */
export function cacheScript(body: string, language: LanguageName): Script {
    return new Script(languageFor(language), body);
}

/** Returns the zstd thread flag. Pass `defaultMulti=true` for backends that default to multi-threaded (e.g. GCS). */
export function threadFlag(c: TaskCacheSpec, defaultMulti = false): string {
    const multi = c.multiThreadCompression ?? defaultMulti;
    return multi ? "-T0" : "-T1";
}

/** Returns the nushell hash-computation expression for the given key files. */
export function hashExpr(c: TaskCacheSpec): string {
    if (c.key.length === 0) {
        return `let hash = ("" | hash sha256 | str substring 0..15)`;
    }
    const keyFileList = c.key.map((f) => `"${f}"`).join(", ");
    return `let hash = (
  [${keyFileList}]
  | each { |f| if ($f | path exists) { open --raw $f } else { "" } }
  | str join | hash sha256 | str substring 0..15
)`;
}

/**
 * Nushell fragment that extracts a cache archive through a staging directory and swaps each
 * cache path into place.
 *
 * Restore used to `rm -rf` every cache path before extracting over it. When the paths live
 * inside a workspace shared with other tasks — the usual layout for language caches pointed at
 * the source workspace (`GOMODCACHE`, `node_modules`, …) — that deletes files another task is
 * reading *right now*, and races its writers (the `rm` itself fails `ENOTEMPTY` while they
 * create files under it). Extracting into a staging directory and renaming makes the swap
 * atomic per path: readers see either the old tree or the new one, never a half-deleted one.
 *
 * @param c        the cache spec, for its `paths`
 * @param label    step label used in log lines
 * @param extract  the extraction pipeline; must write into `$stage` (i.e. `tar xf - -C $stage`)
 */
export function stagedExtract(c: TaskCacheSpec, label: string, extract: string): string {
    const pathList = c.paths.map((p) => `"${p}"`).join(", ");
    return `let stage = $".cache-restore-(random uuid)"
mkdir $stage
try {
  ${extract}
} catch { |e|
  rm -rf $stage
  log $"${label}: extract failed \\(($e.msg)\\)"
  exit 1
}
for p in [${pathList}] {
  let staged = ($stage | path join $p)
  if not ($staged | path exists) { continue }
  if ($p | path exists) {
    # Rename the live tree aside and move the new one in — never delete in place. The
    # displaced tree is removed afterwards and best-effort: a concurrent writer still inside
    # it can legitimately make that fail, and by then nothing resolves to it by path.
    let displaced = $"($p).displaced-(random uuid)"
    mv $p $displaced
    mv $staged $p
    try { ^chmod -R u+w $displaced; rm -rf $displaced } catch { |e|
      log $"${label}: displaced tree ($displaced) not removed: ($e.msg)"
    }
  } else {
    let parent = ($p | path dirname)
    if (($parent | str length) > 0) and ($parent != ".") { mkdir $parent }
    mv $staged $p
  }
}
rm -rf $stage`;
}
